// Sound effects.
//
// The files are generated by scripts/gen-sounds.js — see it for why we
// synthesise rather than download. Loudness is baked into each file, so this
// module only decides WHEN something plays.
//
// Three things here are not obvious, and all three were bugs:
//
//   • the path was a bare `/audio/…`, ignoring BASE_URL, so any build served
//     from a subpath would 404 in silence — which is what has been happening
//     since D8 anyway, because the files did not exist at all
//   • browsers refuse audio before the first user gesture, so early requests
//     have to be DROPPED rather than queued: a queue that empties itself on the
//     first tap is worse than silence
//   • two workers finishing a solder point in the same tick played one clip
//     twice, at double the volume

const BASE = import.meta.env.BASE_URL

// How loud each sound sits in the mix. It multiplies an already-normalised
// file, so the number expresses importance, not level: a sale should land
// harder than a click the player hears fifty times a minute.
const GAIN = {
  order:       0.7,
  solder_good: 0.5,
  solder_cold: 0.7,
  overheat:    1.0,
  sell:        0.9,
  piggy:       0.8,
}

// A phone speaker turns four simultaneous clips into mush, and a busy factory
// asks for more than that.
const MAX_VOICES = 4
// Two of the same sound closer together than this are one event to the ear.
const DEDUPE_MS = 60

let _muted = false
let _unlocked = false
let _voices = 0
const _cache = new Map()
const _lastPlayed = new Map()

function _get(name) {
  if (_cache.has(name)) return _cache.get(name)
  const a = new Audio(`${BASE}audio/${name}.wav`)
  a.preload = 'auto'
  _cache.set(name, a)
  return a
}

export function setMuted(val) { _muted = Boolean(val) }
export function isMuted()     { return _muted }

// Called from the first real gesture. Until then every request is dropped.
export function unlockAudio() { _unlocked = true }

export function playSfx(name) {
  if (_muted || !_unlocked) return
  if (_voices >= MAX_VOICES) return

  const now = performance.now()
  if (now - (_lastPlayed.get(name) ?? -Infinity) < DEDUPE_MS) return
  _lastPlayed.set(name, now)

  try {
    const clone = _get(name).cloneNode()
    clone.volume = GAIN[name] ?? 0.6
    _voices++
    const done = () => { _voices = Math.max(0, _voices - 1) }
    clone.addEventListener('ended', done, { once: true })
    clone.addEventListener('error', done, { once: true })
    clone.play().catch(done)
  } catch {
    // A missing file must never take the frame down with it.
  }
}
